export const LENDING_ABI = {
  address: "0x4512963ba7f24126be6608b9c8081f013e193dc9ac8ccd6679d92c3eda2f4a5f",
  name: "lending",
  friends: [],
  exposed_functions: [
    {
      name: "add_collateral",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address", "u64"],
      return: [],
    },
    {
      name: "withdraw_collateral",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address", "u64"],
      return: [],
    },
    {
      name: "borrow_apex",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address", "u64"],
      return: [],
    },
    {
      name: "repay_apex",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address", "u64"],
      return: [],
    },
    {
      name: "repay_interest",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address"],
      return: [],
    },
    {
      name: "liquidate",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "address", "address"],
      return: [],
    },
  ],
  structs: [],
} as const; 